# SPDX-FileCopyrightText: 2025 Adrian Scarlett
#
# SPDX-License-Identifier: GPL-3.0-only

# Template for host configuration
{ config, pkgs, lib, inputs, ... }: {
  imports = [
    ./hardware-configuration.nix # Will be generated by nixos-generate-config
    ../../modules/system/disk-validation.nix # Validate disk config imports

    # Choose one of:
    # ../../hardware/disko/basic.nix
    # ../../hardware/disko/encrypted.nix
    # ../../hardware/disko/encrypted-yubikey.nix
    
    ./theme.nix                # Stylix theme configuration
  ];

  # Uncomment if using custom disk configuration
  # system.disk.validationEnabled = false;

  # Basic system configuration
  boot = {
    # Boot loader configuration
    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
      };
      efi.canTouchEfiVariables = true;
    };

    # Kernel parameters
    kernelParams = [ ];
    kernelModules = [ ];
  };

  # Hardware configuration
  hardware = {
    # CPU
    cpu.intel.enable = true;  # Change to amd if needed
    
    # GPU - uncomment as needed
    # nvidia.enable = true;
    # amdgpu.enable = true;
    
    # Other hardware features
    bluetooth.enable = true;
    pulseaudio.enable = false; # We use pipewire instead
  };

  # Sound
  sound.enable = true;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Networking
  networking = {
    # Hostname is set automatically from folder structure
    # e.g., hosts/personal/laptop -> laptop-personal
    networkmanager.enable = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ ];
      allowedUDPPorts = [ ];
    };
  };

  # System packages
  environment.systemPackages = with pkgs; [
    # System utilities
    pciutils
    usbutils
    lshw
    dmidecode
    
    # Monitoring
    htop
    iotop
    
    # Network tools
    wget
    curl
    dig
  ];

  # Services
  services = {
    # SSH
    openssh = {
      enable = true;
      settings = {
        PermitRootLogin = "no";
        PasswordAuthentication = false;
      };
    };

    # X11/Wayland
    xserver = {
      enable = true;
      displayManager.gdm.enable = true;
      # Desktop Environment - uncomment one
      # desktopManager.gnome.enable = true;
      # desktopManager.plasma5.enable = true;
      # windowManager.i3.enable = true;
    };
  };

  # User management
  users = {
    mutableUsers = false;  # Manage users through Nix
    users = {
      # Add your users here, or manage through home-manager
      # example = {
      #   isNormalUser = true;
      #   extraGroups = [ "wheel" "networkmanager" ];
      #   openssh.authorizedKeys.keys = [ ];
      # };
    };
  };

  # System state version
  system.stateVersion = "24.11";
}
